version: '3'
services: 
    php:
        image: sand-php
        volumes: 
            - ./:/app
        working_dir: /app
    web:
        image: sand-nginx
        volumes: 
            - ./:/app
            - /data/certs:/etc/nginx/certs
        depends_on: 
            - php
        ports: 
            - 443:443
